# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20161120_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
