# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='_class',
            new_name='classname',
        ),
    ]
