# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20161211_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
